apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  steps:
    - name: checkout
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.repo-url) $(workspaces.source.path)
params:
  - name: repo-url
    type: string
workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-dependencies
spec:
  steps:
    - name: install
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        pip install flake8
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
workspaces:
  - name: source

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        pip install nose
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
workspaces:
  - name: source
